# Generated by Django 5.0.6 on 2024-10-01 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('original_title', models.CharField(max_length=255)),
                ('original_language', models.CharField(max_length=50)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('budget', models.BigIntegerField()),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('homepage', models.URLField(blank=True, null=True)),
                ('vote_average', models.DecimalField(decimal_places=1, max_digits=3)),
                ('vote_count', models.IntegerField()),
                ('production_company_id', models.IntegerField()),
                ('genre_id', models.IntegerField()),
                ('languages', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['release_date'],
            },
        ),
    ]
