# Generated by Django 5.0.6 on 2024-10-01 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_homepage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Moviescontent',
        ),
    ]
